pipeline {
	agent any
    stages {

        stage('Clean') {
            steps {
                echo "Clean Started"
                bat(/mvn -file spring-boot-jwt\/pom.xml clean/)
                echo "Clean End"
            }
        }

        stage('Compile') {
            steps {
                echo "Code Compilation Started"
                bat(/mvn -file spring-boot-jwt\/pom.xml compile/)
                echo "Code Compilation End"
            }
        }
        
        stage('Test') {
            steps {
                echo "Test Started"
                 bat(/mvn -file spring-boot-jwt\/pom.xml org.jacoco:jacoco-maven-plugin:prepare-agent test -Dmaven.test.failure.ignore=true/)
                echo "Test End"
            }
        }

        stage('Jacoco') {
            steps {
                echo "Jacoco Started"
                jacoco classPattern: '**/target/classes', exclusionPattern: '**/*Test*.class', inclusionPattern: '', sourcePattern: '**/src/main'
                echo "Jacoco End"
            }
        }
        
        #stage('SonarQube Analysis') {
            #steps {
                #echo "SonarQube Started"
                #withSonarQubeEnv('localSonarQube') {
                    #bat(/mvn -file spring-boot-jwt\/pom.xml  sonar:sonar  -Dmaven.test.skip=true/)
                #}
                #echo "SonarQube End"
            #}
        #}

        stage('Result') {
            steps {
                echo "Result Started"
                junit '**/spring-boot-jwt/target/surefire-reports/TEST-*.xml'
                echo "Result End"
            }
        }

        stage('Artifact Publish') {
            steps {
                echo "Artifact Publish to Nexus Started"
                bat(/mvn -file spring-boot-jwt\/pom.xml  deploy -Dmaven.test.skip=true/)
                echo "Artifact Publish to Nexus End"
            }
        }
        
        stage('Build Image') {
            steps {
                echo "Build Image Started"
                bat(/mvn -file spring-boot-jwt\/pom.xml package -Dmaven.test.skip=true/)
                bat(/docker build --build-arg VER=0.0.1 -f spring-boot-jwt\/dockerfile -t spring\/spring-boot-jwt:latest ./)
                echo "Build Image End"
            }
        }
        
        stage('Scan Image') {
            steps {
                echo "Scan Image Started"
                bat(/docker scan --file spring-boot-jwt\/dockerfile --json spring\/spring-boot-jwt:latest > spring-spring-boot-jwt_latest.json/)
                echo "Scan Image End"
            }
        }

        stage('Tag Image') {
            steps {
                echo "Tag Image Started"
                bat(/docker tag spring\/spring-boot-jwt:latest hub.docker.local:5000\/spring\/spring-boot-jwt:latest/)
                echo "Tag Image End"
            }
        }

        stage('Push Image') {
            steps {
                echo "Push Image Started"
                bat(/docker push hub.docker.local:5000\/spring\/spring-boot-jwt:latest/)
                echo "Push Image End"
            }
        }

    }
}
